### ISSUE TITLE
Missing the information in "About" field.

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure.ja-jp#16]
Missing the information in "About" field.

Missing the Link to "Github Pages"

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
This is not loclization issue.

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/180975566-8ff350d2-5bb8-4c63-9e61-7fdab1f94a24.png)
